#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class ReturnCode:
  OK = 1
  INVALIDINPUT = 2
  INTERNALERROR = 3

  _VALUES_TO_NAMES = {
    1: "OK",
    2: "INVALIDINPUT",
    3: "INTERNALERROR",
  }

  _NAMES_TO_VALUES = {
    "OK": 1,
    "INVALIDINPUT": 2,
    "INTERNALERROR": 3,
  }

